### PR TITLE
Offer tests

### PR DESCRIPTION
**Pull request by lc512k**
@AdaRoseEdwards

### CODE REVIEW

**Comment by lc512k** [comment]
`npm test` passes locally but tests fail in ci... :/ (in CI the tests seem to be running against the prod instance?)

**Comment by AdaRoseCannon** [comment]
You can use nock to mock the api responses because we don't send any env vars to circleci.

**Comment by AdaRoseCannon** [comment]
nock example: https://github.com/lc512k/chatbot/blob/665a91efe52ce848ec8624944d3aae7b751f7163/test/nock.js

**Comment by lc512k** [comment]
Tests passing,  @AdaRoseEdwards

**Comment by AdaRoseCannon** [comment]
Nice one!!

**Pull request merged**
